Entities/Region.cs
using System.Collections.Generic;

namespace WebApplication2.Entities
{
    public class Region
    {
        public int Id{ get; set; }
        public string Name { get; set; }
        //public string Tribe{ get; set; }
        public int Population{ get; set; }
        public long IGR{ get; set; }
        public virtual List<State> States { get; set; } = new List<State>();
    }
}

Entities/State.cs
namespace WebApplication2.Entities
{
    public class State
    {
        public int Id{ get; set; }
        public string Name { get; set; }
        public string Governor { get; set; }
        public  int RegionId{ get; set; }
        public double StateIGR { get; set; }
        public int Population{ get; set; }
        public Region Region{ get; set; }
        
    }
}

Models/ErrorViewModel.cs
using System;

namespace WebApplication2.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using WebApplication2.Models;

namespace WebApplication2.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel {RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier});
        }
    }
}

Controllers/RegionController.cs
using Microsoft.AspNetCore.Mvc;
using WebApplication2.Entities;
using WebApplication2.Interfaces.Services;

namespace WebApplication2.Controllers
{
    public class RegionController : Controller
    {
        private readonly IRegionServices _regionService;
        private readonly IStateServices _stateServices;

        public RegionController(IRegionServices regionService, IStateServices stateServices)
        {
            _regionService = regionService;
            _stateServices = stateServices;
        }

        public IActionResult Index()
        {
            return View(_regionService.GetAllRegion());
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Region region)
        {
            _regionService.AddRegion(region);
            return RedirectToAction("Index");
        }

        public IActionResult GetRegionDetails(int id)
        {
            var region = _regionService.GetRegion(id);
            if (region == null)
            {
                return NotFound();
            }

            return View(region);
        }

        public IActionResult Update(int id)
        {
            var getRegion = _regionService.GetRegion(id);
            if (getRegion == null)
            {
                return NotFound();
            }

            return View(getRegion);
        }

        [HttpPost]
        public IActionResult Update(Region region, int id)
        {
            _regionService.Update(region, id);
            return RedirectToAction("Index");
        }

        public IActionResult DeleteRegion(int id)
        {
            var delRegion = _regionService.GetRegion(id);
            if (delRegion == null)
            {
                return NotFound();
            }

            return View(delRegion);
        }

        [HttpPost, ActionName("DeleteRegion")]
        public IActionResult DeleteRegion(int id, Region region)
        {
            _regionService.DeleteRegion(id);
            return RedirectToAction("Index");
        }

        public IActionResult GetRegionByState(int id)
        {
            var check = _stateServices.GetRegionByState(id);
            ;
            if (check == null)
            {
                return NotFound();
            }

            var getSate = _stateServices.GetRegionByState(id);
            return View(getSate);
        }

    }
}

Controllers/StateController.cs
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using WebApplication2.Entities;
using WebApplication2.Interfaces.Services;

namespace WebApplication2.Controllers
{
    public class StateController:Controller
    {
        private readonly IStateServices _stateServices;
        private readonly IRegionServices _regionServices;

        public StateController(IStateServices stateServices, IRegionServices regionServices)
        {
            _stateServices = stateServices;
            _regionServices = regionServices;
        }
        public IActionResult Index()
        {
            return View(_stateServices.GetAllState());
        }
        public IActionResult Create()
        {
            var region = _regionServices.GetAllRegion().Distinct();
            
            ViewData["Regions"] = new SelectList(region, "Id", "Name");
            return View();
        }
        [HttpPost]
        public IActionResult Create(State state)
        {
            _stateServices.AddState(state);
            return RedirectToAction("Index");
        }
        public IActionResult GetDetails(int id)
        {
            var region = _stateServices.GetState(id);
            if (region == null)
            {
                return NotFound();
            }

            return View(region);
        }
        public IActionResult Update(int id)
        {
            var getRegion = _stateServices.GetState(id);
            if (getRegion == null)
            {
                return NotFound();
            }

            return View(getRegion);
        }
        [HttpPost]
        public IActionResult Update(State state, int id)
        {
            _stateServices.UpdateState(state, id);
            return RedirectToAction("Index");
        }
        
        public IActionResult DeleteState(int id)
        {
            var delRegion = _stateServices.GetState(id);
            if (delRegion == null)
            {
                return NotFound();
            }
            return View(delRegion);
        }
        [HttpPost,ActionName("DeleteState")]
        public IActionResult DeleteRegion(int id, Region region)
        {
            _stateServices.DeleteState(id);
            return RedirectToAction("Index");
        }

        public IActionResult GetRegionByState(int id)
        {
            var check = _stateServices.GetRegionByState(id);;
            if (check == null)
            {
                return NotFound();
            }

            var getSate = _stateServices.GetRegionByState(id);
            return View(getSate);
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Region/Create.cshtml
<div>
    <form asp-action="Create">
        <div>
            <label>Name</label>
            <input type="text" name="Name" required/>
        </div>
        <div>
            <label>Population</label>
            <input type="number" name ="Population"/>
        </div>
        <div>
            <label>IGR</label>
            <input type="number" name = "IGR"/>
        </div>
        <div>
            <input type="submit" value="submit" class="btn badge-info"/>
        </div>
    </form>
</div>

Views/Region/DeleteRegion.cshtml
@model WebApplication2.Entities.Region
<div>
    <dl>
        <dd>
            Id
        </dd>
        <dt>
            @Model.Id
        </dt>
        <dd>
            Name
        </dd>
        <dt>
            @Model.Name
        </dt>
    </dl>
    <span>Are you sure you want to <b>delete</b>  this state</span>
    <form asp-action="DeleteRegion">
        <input type="hidden" asp-for="Id"/>
        <input type="submit" value="Delete" class="btn btn-danger">
    </form>
    <a asp-action="Index">Go back to list of student</a>
</div>

Views/Region/GetRegionByState.cshtml
@model IEnumerable<WebApplication2.Entities.State>
<div>
    <table class="table">
        <thead>
        <tr>
            <th>Id</th>
            <th>Name</th>
            <th>Governor</th>
            <th>State IGR</th>
            <th>Population</th>
            <th>Region</th>
        </tr>
        </thead>
        <tbody>
        @foreach (var sta in Model)
        {
            <tr>
                <th>@sta.Id</th>
                <th>@sta.Name</th>
                <th>@sta.Governor</th>
                <th>@sta.StateIGR</th>
                <th>@sta.Population</th>
                <th>@sta.Region.Name</th>
            </tr>
        }
        </tbody>

    </table>
</div>

Views/Region/GetRegionDetails.cshtml
@model WebApplication2.Entities.Region
<div>
    <dl>
        <dd>Id</dd>
        <dt>@Model.Id</dt>
        <dd>Name</dd>
        <dt>@Model.Name</dt>
        <dd>Population</dd>
        <dt>@Model.Population</dt>
        <dd>IGR</dd>
        <dt>@Model.IGR</dt>
    </dl>
</div>

Views/Region/Index.cshtml
@model IEnumerable<WebApplication2.Entities.Region>
<div>
    <table class="table">
        <thead>
        <tr>
            <th>Id</th>
            <th>Name</th>
            <th>IGR</th>
            <th>Details</th>
            <th>Edit Region</th>
            <th>Delete Region</th>
            <th>Get State</th>
        </tr>
        </thead>
        <tbody>
        @foreach (var region in Model)
        {
            <tr>
                <th>@region.Id</th>
                <th>@region.Name</th>
                <th>@region.IGR</th>
                <th> <a asp-action="GetRegionDetails" asp-route-Id="@region.Id" class="btn btn-primary">View</a> </th>
                <th><a asp-action="Update" asp-route-id="@region.Id" class="btn btn-primary">Update</a></th>
                <th><a asp-action="DeleteRegion" asp-route-id="@region.Id" class="btn btn-primary">Delete</a></th>
                <th> <a asp-action="GetRegionByState" asp-route-Id="@region.Id" class="btn btn-primary" >Get State</a> </th>
            </tr>
        }
        </tbody>

    </table>
</div>
<div>
    <a asp-controller="Region" asp-action="Create" class="btn btn-dark">Add Region</a>
</div>

Views/Region/Update.cshtml
@model WebApplication2.Entities.Region
<div>
    <form asp-action="Update">
        <div>
            <label>Name</label>
            <input type="text" name="Name" value="@Model.Name" required>
        </div>
        <div>
            <label>Populationl</label>
            <input type="number" name="Population" value="@Model.Population" required>
        </div>
        <div>
            <label>IGR</label>
            <input type="number"  name ="IGR" value="@Model.IGR" required>
        </div>
        <div>
            <input type="submit"  value="Add" class="btn btn-primary" required>
        </div>
        
    </form>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - WebApplication2</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebApplication2</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Region" asp-action="Index">Region</a>
                    </li >
                    <li class="nav-item"> <a class="nav-link text-dark" asp-area="" asp-controller="State" asp-action="Index">State</a> </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2022 - WebApplication2 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/State/Create.cshtml
@model WebApplication2.Entities.State
<div>
    <form asp-action="Create">
        <div>
            <label>Name</label>
            <input type="text" name="Name" required/>
        </div>
        <div>
            <label>Governor</label>
            <input type="text" name ="Governor" required/>
        </div>
        <div>
            <label>State IGR</label>
            <input type="number" name = "StateIGR" required/>
        </div>
        <div>
            <label>Population</label>
            <input type="number" name = "Population"/>
        </div>
        <div>
            <label>Region</label>
            <select asp-for="RegionId" asp-items="ViewBag.Regions"></select>
        </div>
        <div>
            <input type="submit" value="submit" class="btn badge-info"/>
        </div>
    </form>
</div>

Views/State/DeleteState.cshtml
@model WebApplication2.Entities.State
<div>
    <dl>
        <dd>
            Id
        </dd>
        <dt>
            @Model.Id
        </dt>
        <dd>
            Name
        </dd>
        <dt>
            @Model.Name
        </dt>
    </dl>
    <span>Are you sure you want to <b>delete</b> this State</span>
    <form asp-action="DeleteState">
        <input type="hidden" asp-for="Id"/>
        <input type="submit" value="Delete" class="btn btn-danger">
    </form>
    <a asp-action="Index">Go back to list of student</a>
</div>

Views/State/GetDetails.cshtml
@model WebApplication2.Entities.State
<div>
    <dl>
        <dd>Id</dd>
        <dt>@Model.Id</dt>
        <dd>Name</dd>
        <dt>@Model.Name</dt>
        <dd>Population</dd>
        <dt>@Model.Population</dt>
        <dd>IGR</dd>
        <dt>@Model.StateIGR</dt>
        <dd>Region</dd>
        <dt>@Model.RegionId</dt>
    </dl>
</div>

Views/State/GetRegionByState.cshtml
@model IEnumerable<WebApplication2.Entities.State>
<div>
    <table class="table">
        <thead>
        <tr>
            <th>Id</th>
            <th>Name</th>
            <th>Governor</th>
            <th>State IGR</th>
            <th>Population</th>
            <th>Region</th>
        </tr>
        </thead>
        <tbody>
        @foreach (var sta in Model)
        {
            <tr>
                <th>@sta.Id</th>
                <th>@sta.Name</th>
                <th>@sta.Governor</th>
                <th>@sta.StateIGR</th>
                <th>@sta.Population</th>
                <th>@sta.Region.Name</th>
            </tr>
        }
        </tbody>

    </table>
</div>

Views/State/Index.cshtml
@model IEnumerable<WebApplication2.Entities.State>
<div>
    <table class="table">
        <thead>
        <tr>
            <th>Id</th>
            <th>Name</th>
            <th>Governor</th>
            <th>State IGR</th>
            <th>Details</th>
            <th>Edit State</th>
            <th>Delete</th>
            <th>Get Region</th>
        </tr>
        </thead>
        <tbody>
        @foreach (var sta in Model)
        {
            <tr>
                <th>@sta.Id</th>
                <th>@sta.Name</th>
                <th>@sta.Governor</th>
                <th>@sta.StateIGR</th>
                <th> <a asp-action="GetDetails" asp-route-id="@sta.Id" class="btn  btn-info">View</a> </th>
                <th><a asp-action="Update" asp-route-id="@sta.Id" class="btn btn-secondary">Update</a></th>
                <th><a asp-action="DeleteState" asp-route-id="@sta.Id" class="btn btn-danger ">Delete</a></th>
                <th> <a asp-action="GetRegionByState" asp-route-Id="@sta.RegionId" class="btn btn-primary " >Get Region</a> </th>
            </tr>
        }
        </tbody>

    </table>
</div>
<div>
    <a asp-controller="State" asp-action="Create" class="btn btn-dark">Add State</a>
</div>

Views/State/Update.cshtml
@model WebApplication2.Entities.State
<div>
    <form asp-action="Update">
        <div>
            <label>Name</label>
            <input type="text" name="Name" value="@Model.Name" required>
        </div>
        <div>
            <label>Governor Name</label>
            <input type="text" name="Governor" value="@Model.Governor" required>
        </div>
        <div>
            <label>Population</label>
            <input type="number"  name ="Population" value="@Model.Population" required>
        </div>
        <div>
            <label>IGR</label>
            <input type="number"  name ="StateIGR" value="@Model.StateIGR" required>
            </div>
        <div>
            <input type="submit"  value="Add" class="btn btn-primary" required>
        </div>
        
    </form>
</div>